delete from account_details where username = 'johndoe';
delete from account_details where username = 'janedoe';
delete from account_details where username = 'marydoe';
delete from account_details where username = 'justinedoe';
delete from account_details where username = 'juantee';
delete from account_details where username = 'pedrostone';
delete from account_details where username = 'therock';
delete from account_details where username = 'lukeatme';
delete from account_details where username = 'aimeelao';
delete from account_details where username = 'aimeelao123';
select * from account_details;